### ISSUE TITLE
hangs when BadWordsList contains an empy string, exception if contains null;

### ISSUE THREAD

**Issue by slavapvf** [rebeccapowell/csharp-algorithm-coupon-code#2]
hi, i am generatings set of unique promocodes and fill BadWordsList dinamically:

                var list = new List<string>(100);
                var opts = new Options();
                var ccb = new CouponCodeBuilder();
                ccb.BadWordsList = new string[model.Count + existingCodes.Count];
                for (int i = 0; i < 100; i++)
                {
                    ccb.BadWordsList[existingCodes.Count + i] = string.Empty;
                }
                for (int i = 0; i < 100; i++)
                {
                    var code = ccb.Generate(opts);
                    list.Add(code);
                    ccb.BadWordsList[i] = code;
                }

so this code hangs.

Also it would be useful use BadWordsList as a HashSet or a delegate or make the method ContainsBadWord virtual in order to check it against the data in a database.

**Comment by precary** [comment]
Maybe it help someone, i change this.ContainsBadWord(string.Join(string.Empty, parts.ToArray())) with   ContainsBadWord(parts.Aggregate((a, b) => a + string.Empty + b)) and   return string.Join("-", parts.ToArray()); with  parts.Aggregate((a, b) => a + "-" + b);

**Comment by rebeccapowell** [comment]
Please see updated tests for the fix. Should be available in 1.0.5.
